language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: ux0aHKBGzssEUvSSIP93dZtK9GCVgKQAjr+5zCIusVLmPhVmvWgYaB2sZ+vKUiqh4TyLyFSRGhBbmD4/tR7KgIH7gN6retFpQCDSxHUT0feCOFYzpd7Vm4bctmG4lY0347X+d67Bt80mSZabEYkx8Xe4g7mhrLdV/Crxee+yedfdAeMTQE0uHEUZjTGcQqNqhB0l4QYi1Vv7Xe62A8rSFIFmJYIxOrEPmzbtz5KyxKjylXslr9iJu8q0q/ubSaAeEvWas4LHaIXlE+t3/xgg9gqE7+lcBkWU02rV+TAjOebLAknilT9BJraqskILBtD8qfNIWpB/k7JyaDgh/cjPUU0mz1VPAo2zUE8kgCM0vF1dnji8ZWeGpNNE8SB3TIibsUnI/LL0BgYfa71rDgIpmZlMzWkRPvdz31O25LBsW0BpDJoUEvp6f3kj9GZ7sUTf9O1+ng/Gud7k3FD4x5AHLKDsf2ATTAb63+hjrfF0vSAm2QTK4aZABxxKv32sgyMcITrRSTBGIWdfpHQxObicYW/7g8GkOxO03p41oRbl5K3SsaOMJXR2mA/T0aTzNVQCIQygYfCha2ghhjo64ox3z+ziCer/vrPblUZA10t59E7d94I+BwtuiSFZYRP2kt1OmgsAaIpc7jz6Rj4ocE19nGuT1qDY/UODeFgMox/v2TA=
  app: calm-refuge-16149
  run: rails db:migrate
  on:
    repo: ajtran303/movie_night
    branch: main
env:
  global:
    secure: zMqDsQ0KXWSXAsc+qKbdQqZYJEZEQ7bgVIrxVdFyAEdbnvsBN+GeOBsyCK/C2JUy3YqpPi/lIMQjlmZMl9kwLX3rPwWmSCv55dMFhHpWBjvZzGGgnk7n6lcwTEnlTntKbT5QPOVeKhf+Fj2mhM6uqmvrJtiTBbsLGHmlpSkSgVheFjhTwTYgv5S/IS1JEMmPIkl+hbieguFRELxbc4KKVOwc+1L25ZJWWz2x97ND1PDVaFSRtGV9WHzcgRZwZP+jnWEvPWvHlPV4gKv4VWbgevqFmzbATZOyT7kmCcBSTmilcFxQ5In+R2AVHKosIj+HvWZXsW+GaCBcr6eD0Jl/SIvaiIzOhQ1DGRL3PpJM8mOq5Q53pDetWIzuromo9smZvT2jQe4fKv7RaDd1dH5BQLJ2XyBuNsnpAB796UBPwkkFa+r97F/v7COIWOEWlxqCogHT/BUAYNkrGw3vR4tkA/rM1L7z2xWJxmBT9dpBundTGmBSV3aQS0nopfouGJSwwOXlH89DLzy9bUpRzQ34hsDylBsg7nfVqkr5zmbUGeJzT0qQEkA2S+enAGb3Va/nYkiCbCNZUITwKb3QZkZTBuyBTh0AxW8aSAR77mIvQGzpNDv0UXfC4+JlpdcO+Av/wYT2teismecBv3JAvsKxVxJYOhqloZDVe7KWlVRcVNw=
