language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: f1xczwgEfNPAxinMtoHspX2hskp2/ySaDzRj2tkKAiZVcnNLnLHBSWPyw4AAEhOE3kzY6y8tDHHFy5BGJBBA12dsn6yuRO0bzZVOEbykqnqpf48IIKbQjHrV3EgSBb0uqtXAxWUsU8Gr3koBZf07BNn4sn00EwFKdz1Bolx8N81pXGhjlyKAA8ot73QvRdTGrpQxds4tj3PoicR+HT61nA6ojOozps1B2ixsvNFU/xqABeF2XCcouxLqxS0iZj/bdccJPylMRRiI7sxxfQAfFcvV6XsHnNpeFEmI0CM+VP3LRXuDe3P35UD9NQpywbcKbWf8gAA8v752jQF7rT5glk7vmMGCawrZYtUa/0Ws/bIuy7i7cjcgsrzy9b4DsD0uNHmcDjPQbOBQolOEJBXhcp0DXNZ2x4/gvwZrSNzhlQMpe/CXZWuNeZMfBki8nfMb/ur/0BBAZdk+PvWS+b698X229pE7mobkGEXs9a1ekewcVmQ+3K66sLCKHwH/w2FothEU9m+XJbzkGu5y3smhi1/aLw7yhupnJmSchgqqntaKiHcmY0pW5DUwGmVvIMtxFTsJ9+3vY33TcxDW4I0R7eL4upFb/2RN4BtidAIwNnabW9bioY6mCW8FC57feXlEoC6zIva+XP5dw7acR9crbjMq1rAiQXIKlmL3aYmUrGo=
  app: gentle-cove-40318
  run: rails db:migrate
  on:
    repo: ajtran303/viewing_party
    branch: main
env:
  global:
    secure: OgyB64Oos/EL2M8ExTJHDhUUrIn2ODRnFZd5kd8PdnTh0YoTMLZdIguscjHhteEt2Bq0vJ8BFBHWhF3qLip3j3HO/Yxh/fhc055TXJuE9WIGgJyPLZkf3DIE7+9z5j5uJM1+f7CYMEfSVPcRTlQQNdByc7NJa+7tRoFlhPGeegL7k8Huvvdd/OWOwJkT38/qB0VwN8530HdcnHe9NeoDO0GEp1xdASf6WcY85leuOMutOqaaa6LlnA8nSMtp2Z0ntd8G438bsUeNtn7TaEZQFlC2g10bue+OC3EuxRGbcs0xu2l7kqfbkBVa0pZvWr4YrqKCFgSayc8jSFw5sWpQ43jRN9zJ2EZAq6Sdqg+dGPR2rorKr/U995ucePNRf/i7dyGXlKC6I6WP9Nv028b+F6X/WOfJ7wz1UQUPDa2YJ//hnNHzDIUMXrI/onMmsYZqGJE8R0/3fxpHrd0LKBkfzDsAlfF2ROK5P3MUFSMJtIqlG4YQGap9XPplI3KkJ7wvpkhYa2CA4ihVQ0Buw6+Evd3dWb7Asy5pbutfP2ImInGXV7foxOdtIBIW6xyEG8yuvWQY7zzgCHlQDbboJUEdN5BzTdXm70yc1jYmtQnVIwxUHYoGuM+Rlwufoqf99ebbZ+4dVooMaT3bIbtkZfT+yxOdg3KJ7bcyL2Bnq8P0csY=
